name: Send weekly call notifications every Thursday at 1 pm
on:
  schedule:
    - cron: "0 13 * * 4"
    # Correct cron schedule: "0 13 * * 4"
    # For testing: "*/5 * * * *"
  workflow_dispatch:

jobs:
  email:
    runs-on: macos-14
    steps:
      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.0
        with:
          deno-version: latest

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: latest

      - name: Checkout branch    
        uses: actions/checkout@v4

      - name: Install packages
        uses: actions/setup-node@v4
        with:
          cache: pnpm

      - name: Install ndnts-aux
        run: |
          echo "@ucla-irl:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=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" >> .npmrc
          rm pnpm-lock.yaml
          pnpm i
        env:
          NODE_AUTH_TOKEN: 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
        
      - name: Run script
        run: ./get_info_testbed.bash
