name: Send weekly call notifications every Thursday at 1 pm
on:
  schedule:
    - cron: "0 13 * * 4"
    # Correct cron schedule: "0 13 * * 4"
    # For testing: "*/5 * * * *"
  workflow_dispatch:

jobs:
  email:
    runs-on: macos-14
    steps:
      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.0

      - name: Checkout branch    
        uses: actions/checkout@v4

      - name: Install packages
        uses: actions/setup-node@v4

      - name: Deno install
        run: deno install node_modules/nodemailer
        
      - name: Run script
        run: ./get_info_testbed.bash
