name: Send weekly call notifications every Thursday at 1 pm
on:
  schedule:
    - cron: "*/5 * * * *"
    # Correct cron schedule: "0 13 * * 4"
    # For testing: "*/5 * * * *"

jobs:
  email:
    runs-on: macos-14
    steps:
      - name: run script
        working-directory: ${{ github.workspace }}
        run:
          ./get_info_testbed.bash
